apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-python-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rarnaud-tenant/prod1/rhtap-python-sample@sha256:370318dae82ee9ad89fc79eb1b3bb1c00873a07afc22d6886e4fc1dd9f8847eb
        name: my-python
        resources: {}
status: {}
