apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-python-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rarnaud-tenant/prod1/rhtap-python-sample@sha256:9fd055a9cb0cc1e61ed56ccdfebfc1f1764d605ff267b902191a43821afe7156
        name: my-python
        resources: {}
status: {}
